#
#
version: '3.1'
#
services:
#    
  spark-master:
    image: spark:3.0.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - /apps/hostpath:/d/apps/hostpath
      - /apps/hostpath/spark:/usr/local/spark/work-dir
    environment:
      NODE_TYPE: MASTER
      WEBUI_PORT: 8080

#
  spark-node01:
    image: spark:3.0.1
    container_name: spark-node01
    hostname: spark-node01
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    volumes:
      - /apps/hostpath:/d/apps/hostpath
      - /apps/hostpath/spark:/usr/local/spark/work-dir
    environment:
      NODE_TYPE: WORKER
      WEBUI_PORT: 8081

#
#  spark-node02:
#    image: spark:3.0.1-3.2.0
#    container_name: spark-node02
#    hostname: spark-node02
#    depends_on:
#      - spark-master
#    ports:
#      - 8082:8082
#    volumes:
#      - /apps/hostpath:/d/apps/hostpath
#      - /apps/hostpath/spark:/usr/local/spark/work-dir
#    environment:
#      NODE_TYPE: WORKER
#      WEBUI_PORT: 8082
#

#
  namenode:
    image: hadoop:3.2.0
    container_name: namenode
    ports:
      - "9000:9000"
      - "9866:9866"  
      - "9870:9870"
      - "9864:9864" 
    command: /usr/local/bin/start-hdfs.sh
    hostname: namenode
    volumes:
      - /apps/hostpath/spark/data:/data
      - /apps/hostpath:/d/apps/hostpath
    environment:
      HDFS_MODE: SingleNode  

#
#  hive:
#    image: hadoop:3.1.2
#    container_name: hive
#    hostname: hiveserver
#    command: /usr/local/bin/start-hive.sh
##    restart: always
#    depends_on:
#      - mysqlserver
#    volumes:
#      - /apps/hostpath/hive/warehouse:/user/hive/warehouse
#      - /apps/hostpath:/d/apps/hostpath
#    environment:
#      DATA_DIR: /user/hive/warehouse
#    ports:
#      - 10000:10000
#      - 9083:9083


#  history-server:
#    image: spark:3.0.1-3.2.0
#    container_name: history-server
#    hostname: history-server
#    depends_on:
#      - spark-master
#    ports:
#      - 18080:18080
#    volumes:
#      - /apps/hostpath/spark:/d/apps/hostpath/spark
#    environment:
#      NODE_TYPE: LOGSERVER

#
#networks:
#  default:
#    external:
#      name: bridge  
#  backend:
#    driver: bridge
# 